FROM continuumio/miniconda3

RUN conda create -q --yes --strict-channel-priority -n unifrac -c conda-forge -c bioconda gxx_linux-64 gfortran_linux-64 hdf5 mkl-include lz4 zlib hdf5-static libcblas liblapacke make curl git ; conda activate unifrac; git clone --depth 1 https://github.com/biocore/unifrac-binaries.git; cd unifrac-binaries; ./scripts/install_hpc_sdk.sh </dev/null; export PERFORMING_CONDA_BUILD=True; export BUILD_OFFLOAD=acc; make all; rm -fr hpc_sdk

